---
- include_vars:                   secrets.yml

- name:                           install dependencies
  pip:
    name:                         '{{ item }}'
    state:                        present
  with_items:                     '{{ aws_dependencies.pip }}'

- name:                           spin up ec2 instance
  ec2:
    aws_access_key:               '{{ aws_access_key }}'
    aws_secret_key:               '{{ aws_secret_key }}'
    image:                        '{{ aws_image }}'
    instance_type:                '{{ aws_instance_type }}'
    wait:                         yes
    region:                       '{{ aws_region }}'
    assign_public_ip:             yes
    vpc_subnet_id:                '{{ aws_vpc_id }}'
    exact_count:                  1
    key_name:                     exercise-1
    instance_tags:
      class:                      '{{ ec2_tag }}'
    count_tag:
      class:                      '{{ ec2_tag }}'

- name:                           gather ec2 facts
  ec2_remote_facts:
    aws_access_key:               '{{ aws_access_key }}'
    aws_secret_key:               '{{ aws_secret_key }}'
    region:                       '{{ aws_region }}'
    filters:
      'tag:class':                '{{ ec2_tag }}'
      instance-state-name:        running
  register:                       ec2_info

- name:                           add host to aws group
  add_host:
    hostname:                     '{{ item.public_ip_address }}'
    groupname:                    ec2
    ansible_ssh_private_key_file: '{{ aws_ssh_key }}'
  with_items:                     '{{ ec2_info.instances }}'

- name:                           wait for ssh to come up
  wait_for:
    host:                         '{{ item.public_ip_address }}'
    port:                         22
    delay:                        0
    timeout:                      320
    state:                        started
  with_items:                     '{{ ec2_info.instances }}'
