---
- name:       install yum dependencies
  yum:        name={{ item }} state=present
  with_items: '{{ docker_dependencies.yum }}'

- name:       ensure docker python support is installed
  pip:        name={{ item }} state=present
  with_items: '{{ docker_dependencies.pip }}'

- name:       start docker
  service:
    name:     docker
    state:    started
    enabled:  yes
