---
- name:        set up ec2
  hosts:       controller
  roles:
    - aws
- name:        run ansible
  hosts:       ec2
  remote_user: ec2-user
  become:      yes
  become_user: root
  roles:
    - docker
    - mysql
    - nginx
    - wordpress
